---
apiVersion: kubeadm.k8s.io/v1beta2
kind: JoinConfiguration
discovery:
  bootstrapToken:
    token: ${KUBEADM_TOKEN}
    apiServerEndpoint: "${API_URL}:6443"
    unsafeSkipCAVerification: true
nodeRegistration:
  name: NODE_NAME
  kubeletExtraArgs:
    cloud-provider: ${CLOUD_PROVIDER}
    node-ip: NODE_IP